### ISSUE TITLE
Change repo to nf-core/actions

### ISSUE THREAD

**Issue by edmundmiller** [nf-core/setup-nextflow#22]
> Personally, I would love to see all nf-core testing workflows updated to use one install per repo per version, and then all tests are run off of that. I'm really inspired by [Julia's testing workflow template](https://github.com/JuliaCI/PkgTemplates.jl/blob/master/templates/github/workflows/CI.yml). Unfortunately, Nextflow doesn't have as nice of a testing framework as Julia, so that may be a pipe dream.

> That's nice. Do you not think that would work with nf-test?

> That also makes me think we could move to a repo and pull in the GitHub actions like this repo https://github.com/magit/actions so it would just be:

```yaml
steps:
    steps:
      - name: Install Nextflow
        uses: nf-core/actions/setup-nextflow@main
      - name: Install nf-core
        uses: nf-core/actions/setup-nf-core@main
      - name: Run nf-test
        uses: nf-core/actions/nf-test@main
```

_Originally posted by @Emiller88 in https://github.com/nf-core/setup-nextflow/issues/19#issuecomment-1701214197_
